name: Build and push Containerfile
runs-on: ubuntu-24.04
on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * 3"
steps:
- name: Update and install podman
  run: sudo apt-get update && sudo apt-get install podman make

- name: Login to Quay
  env:
    CONTAINER_REPOSITORY: ${{ vars.CONTAINER_REPOSITORY }}
    CONTAINER_REPOSITORY_USERNAME: ${{ vars.CONTAINER_REPOSITORY_USERNAME }}
    QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
  run: podman login -u "$CONTAINER_REPOSITORY_USERNAME" --password "$QUAY_IO_PASSWORD" "$CONTAINER_REPOSITORY"

- name: Build bootc image
  env:
    BOOTC_IMAGE_NAME: ${{ vars.CONTAINER_REPOSITORY_USERNAME }}
    IMAGE_TARGET: ${{ vars.BOOTC_IMAGE_TARGET }}
  run: make build-bootc-container

- name: Push bootc image
  env:
    BOOTC_IMAGE_NAME: ${{ vars.CONTAINER_REPOSITORY_USERNAME }}
    IMAGE_TARGET: ${{ vars.BOOTC_IMAGE_TARGET }}
  run: podman push "${BOOTC_IMAGE_NAME}:${IMAGE_TARGET}
