name: Build and push development toolbox
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 3"
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Update and install podman
      run: sudo apt-get update && sudo apt-get install podman make

    - name: Login to Quay
      env:
        CONTAINER_REPOSITORY: ${{ vars.CONTAINER_REPOSITORY }}
        CONTAINER_REPOSITORY_USERNAME: ${{ vars.CONTAINER_REPOSITORY_USERNAME }}
        QUAY_IO_PASSWORD: ${{ secrets.QUAY_IO_PASSWORD }}
      run: podman login -u "$CONTAINER_REPOSITORY_USERNAME" --password "$QUAY_IO_PASSWORD" "$CONTAINER_REPOSITORY"

    - name: checkout repo
      uses: actions/checkout@main

    - name: Build toolbox
      env:
        TOOLBOX_IMAGE_NAME: ${{ vars.TOOLBOX_IMAGE_NAME }}
        TOOLBOX_IMAGE_TAG: ${{ vars.TOOLBOX_IMAGE_TAG }}
      run: make build-toolbox-container

    - name: Push toolbox
      env:
        TOOLBOX_IMAGE_NAME: ${{ vars.TOOLBOX_IMAGE_NAME }}
        TOOLBOX_IMAGE_TAG: ${{ vars.TOOLBOX_IMAGE_TAG }}
      run: podman push "${TOOLBOX_IMAGE_NAME}:${TOOLBOX_IMAGE_TAG}"
